### ISSUE TITLE
change query of schema.sql

### ISSUE THREAD

**Issue by ghost** [ufasoli/spring-mvc-swagger-tutorial#1]
Could you please change query of "schema.sql" ? I see it's syntactically not correct, Please find below the correct query...

CREATE TABLE BOOKS (
id VARCHAR(255) NOT NULL, 
title VARCHAR(255) NOT NULL, 
author VARCHAR(255) NOT NULL, 
publicationYear INTEGER, 
comment VARCHAR(255), 
PRIMARY KEY(id)
)

Just making one change for "publicationYear" field.

**Comment by ufasoli** [comment]
Hi, 
Thanks for the input, I updated the script now.
